module.exports = {
  STATES: {
    DID_NOT_UNDERSTAND_STATE: "_DID_NOT_UNDERSTAND_STATE",
    GUESS_MY_NUMBER_STATE: "_GUESS_MY_NUMBER",
    MESSAGE_STATE: "_SEND_MESSAGE_STATE",
    SING_LULLABY_STATE: "_SING_LULLABY_STATE",
    TALE_STATE: "_TALE_STATE",
    TALE_INTRO_STATE: "_TALE_INTRO_STATE",
    TALE_CHOICE_STATE: "_TALE_CHOICE_STATE",
    TALE_PLAY_STATE: "_TALE_PLAY_STATE",
    WELCOME_STATE: "_WELCOME",
  }
};
