module.exports = {
  STATES: {
    WELCOME_STATE: "_WELCOME",
    GUESS_MY_NUMBER_STATE: "_GUESS_MY_NUMBER",
    MESSAGE_STATE: "_SEND_MESSAGE_STATE",
    SING_LULLABY_STATE: "_SING_LULLABY_STATE"
  }
};
