module.exports = {
  STATES: {
      DID_NOT_UNDERSTAND_STATE: "_DID_NOT_UNDERSTAND_STATE",
      GUESS_MY_NUMBER_STATE: "_GUESS_MY_NUMBER",
      MESSAGE_STATE: "_SEND_MESSAGE_STATE",
      SING_LULLABY_STATE: "_SING_LULLABY_STATE",
      WELCOME_STATE: "_WELCOME"
  }
};
